if (${MCU_NAME} MATCHES "^ATXMEGA128D4$|^ATXMEGA384C3$|^ATXMEGA256A3$|^ATXMEGA256A3U$|^ATXMEGA192C3$|^ATXMEGA192A3$|^ATXMEGA192A3U$|^ATXMEGA256A3BU$|^ATXMEGA256D3$|^ATXMEGA384D3$|^ATXMEGA192D3$|^ATXMEGA128A1$|^ATXMEGA128A1U$|^ATMEGA2561$|^ATXMEGA128A3$|^ATMEGA2560$|^ATXMEGA128C3$|^ATXMEGA128A4U$|^ATXMEGA128B1$|^ATXMEGA256A3B$|^ATXMEGA128B3$|^ATXMEGA128D3$|^ATXMEGA256C3$|^ATXMEGA128A3U$")


    if (NOT TARGET MikroC.STMPE610 )
        add_library(__Lib_STMPE610 UNKNOWN IMPORTED)
    endif()
    set_target_properties(__Lib_STMPE610 PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "MikroC"
    IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/../bin/GT64K/__Lib_STMPE610/__Lib_STMPE610.mcl"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/../bin/GT64K/__Lib_STMPE610")

    set(MikroC.STMPE610_DEFINITIONS )


    if (NOT TARGET MikroC.STMPE610 )
        add_library(MikroC.STMPE610 INTERFACE)
    endif()

    target_link_libraries(MikroC.STMPE610 INTERFACE __Lib_STMPE610)
    set(MikroC.STMPE610_LIBRARIES "\"${CMAKE_CURRENT_LIST_DIR}/../bin/GT64K/__Lib_STMPE610/__Lib_STMPE610.mcl\"")


    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(MikroC.STMPE610  DEFAULT_MSG
                                    MikroC.STMPE610_LIBRARIES)


    set(MikroC.STMPE610_INCLUDE_DIRS ${MikroC.STMPE610_INCLUDE_DIR} )



    list(APPEND LEGACY_LIBRARIES_LIST ${MikroC.STMPE610_LIBRARIES})
    
    list(JOIN LEGACY_LIBRARIES_LIST " " LEGACY_LIBRARIES_JOINED)
    set(LEGACY_LIBRARIES ${LEGACY_LIBRARIES_JOINED} CACHE STRING "" FORCE)
    ## Since mikroC cmd line needs mcl files to compile object, only way to pass those mcl files to cmake was through compiler flags.
    set( CMAKE_MikroC_FLAGS "${CMAKE_MikroC_FLAGS} ${LEGACY_LIBRARIES}")
    
    # removing duplacates from CMAKE_MikroC_FLAGS
    separate_arguments (separated NATIVE_COMMAND "${CMAKE_MikroC_FLAGS}")
    list(REMOVE_DUPLICATES separated)
    list(TRANSFORM separated PREPEND "\"")
    list(TRANSFORM separated APPEND "\"")

    list(JOIN separated " " joined)
    set(CMAKE_MikroC_FLAGS ${joined})
    unset(separated)
    unset(joined)

    
endif()

if (${MCU_NAME} MATCHES "^AT90USB646$|^AT90CAN128$|^ATMEGA88A$|^ATXMEGA32A4U$|^ATXMEGA64C3$|^ATMEGA324A$|^ATTINY814$|^ATMEGA168PA$|^ATTINY816$|^ATXMEGA64A4U$|^ATMEGA168A$|^AT90CAN64$|^ATTINY817$|^ATMEGA16HVB$|^ATMEGA164$|^ATMEGA16$|^ATXMEGA64B1$|^ATMEGA324PB$|^ATMEGA168P$|^AT90CAN32$|^ATMEGA1284P$|^ATMEGA8$|^ATXMEGA32A4$|^ATXMEGA32C4$|^ATMEGA32$|^ATMEGA1281$|^ATMEGA324$|^ATMEGA88PA$|^ATMEGA8535$|^ATXMEGA32E5$|^ATXMEGA8E5$|^ATMEGA168PB$|^ATMEGA16U4$|^ATMEGA406$|^ATMEGA128A$|^ATMEGA644A$|^ATXMEGA32C3$|^ATXMEGA64A3U$|^ATMEGA1284$|^ATMEGA64A$|^ATMEGA164PA$|^ATXMEGA64D4$|^ATMEGA328P$|^AT90USB647$|^ATMEGA1280$|^ATXMEGA16D4$|^AT90USB1286$|^ATTINY88$|^ATXMEGA64A1$|^ATXMEGA64A1U$|^ATXMEGA16A4U$|^ATMEGA644P$|^AT90USB1287$|^ATMEGA163$|^ATXMEGA16A4$|^ATXMEGA32D3$|^ATMEGA32HVB$|^ATMEGA32A$|^ATXMEGA64D3$|^ATMEGA164A$|^ATMEGA323$|^ATMEGA88PB$|^ATMEGA164P$|^ATMEGA644$|^ATMEGA88$|^ATMEGA32U4$|^ATMEGA640$|^ATMEGA128$|^ATMEGA8A$|^ATXMEGA64A3$|^ATMEGA168$|^ATMEGA16A$|^ATMEGA324P$|^ATMEGA88P$|^ATXMEGA32D4$|^ATMEGA328PB$|^ATMEGA64$|^ATXMEGA16E5$|^ATMEGA32U6$|^ATXMEGA64B3$|^ATXMEGA16C4$|^ATMEGA328$|^ATMEGA644PA$|^ATMEGA324PA$")


    if (NOT TARGET MikroC.STMPE610 )
        add_library(__Lib_STMPE610 UNKNOWN IMPORTED)
    endif()
    set_target_properties(__Lib_STMPE610 PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "MikroC"
    IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/../bin/LTE64K/__Lib_STMPE610/__Lib_STMPE610.mcl"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/../bin/LTE64K/__Lib_STMPE610")

    set(MikroC.STMPE610_DEFINITIONS )


    if (NOT TARGET MikroC.STMPE610 )
        add_library(MikroC.STMPE610 INTERFACE)
    endif()

    target_link_libraries(MikroC.STMPE610 INTERFACE __Lib_STMPE610)
    set(MikroC.STMPE610_LIBRARIES "\"${CMAKE_CURRENT_LIST_DIR}/../bin/LTE64K/__Lib_STMPE610/__Lib_STMPE610.mcl\"")


    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(MikroC.STMPE610  DEFAULT_MSG
                                    MikroC.STMPE610_LIBRARIES)


    set(MikroC.STMPE610_INCLUDE_DIRS ${MikroC.STMPE610_INCLUDE_DIR} )



    list(APPEND LEGACY_LIBRARIES_LIST ${MikroC.STMPE610_LIBRARIES})
    
    list(JOIN LEGACY_LIBRARIES_LIST " " LEGACY_LIBRARIES_JOINED)
    set(LEGACY_LIBRARIES ${LEGACY_LIBRARIES_JOINED} CACHE STRING "" FORCE)
    ## Since mikroC cmd line needs mcl files to compile object, only way to pass those mcl files to cmake was through compiler flags.
    set( CMAKE_MikroC_FLAGS "${CMAKE_MikroC_FLAGS} ${LEGACY_LIBRARIES}")
    
    # removing duplacates from CMAKE_MikroC_FLAGS
    separate_arguments (separated NATIVE_COMMAND "${CMAKE_MikroC_FLAGS}")
    list(REMOVE_DUPLICATES separated)
    list(TRANSFORM separated PREPEND "\"")
    list(TRANSFORM separated APPEND "\"")

    list(JOIN separated " " joined)
    set(CMAKE_MikroC_FLAGS ${joined})
    unset(separated)
    unset(joined)

    
endif()

